CRITICAL - 2025-02-18 19:46:39 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "includes/note_message.php"
[Method: GET, Route: settings/google_maps/]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('includes/note_message.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('includes/note_message', [], true)
 3 APPPATH\Views\settings\integration\google_maps.php(41): view('includes/note_message', [...])
 4 SYSTEMPATH\View\View.php(234): include('C:\\wamp64\\www\\palava_hut\\app\\Views\\settings\\integration\\google_maps.php')
 5 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('settings/integration/google_maps', [], true)
 7 APPPATH\Libraries\Template.php(38): view('settings/integration/google_maps', [...])
 8 APPPATH\Controllers\Settings.php(1592): App\Libraries\Template->view('settings/integration/google_maps')
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Settings->google_maps()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-02-18 21:02:52 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(35): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('enable_maps_set...', '')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:02:52 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(35): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('maps_settings_a...', 'AIzaSyA8pb0_xeF...')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:06:41 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('enable_maps_set...', '')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:06:41 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('maps_settings_a...', 'AIzaSyA8pb0_xeF...')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:07:44 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('enable_maps_set...', '')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:07:44 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('maps_settings_a...', 'AIzaSyA8pb0_xeF...')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:57:49 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('enable_maps_set...', '')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 21:57:49 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('maps_settings_a...', 'AIzaSyA8pb0_xeF...')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 22:08:53 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Settings.php(1610): App\Models\Settings_model->save_setting('enable_maps_set...', '')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Settings->save_google_maps_settings()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Settings))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 22:12:55 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Dashboard.php(49): App\Models\Settings_model->save_setting('user_2_dashboar...', '', 'user')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Dashboard->index('1')
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 22:23:51 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Dashboard.php(49): App\Models\Settings_model->save_setting('user_2_dashboar...', '', 'user')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Dashboard->index('1')
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 23:01:41 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Dashboard.php(49): App\Models\Settings_model->save_setting('user_2_dashboar...', '', 'user')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Dashboard->index()
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-02-18 23:02:06 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\wamp64\www\palava_hut\system\Database\MySQLi\Connection.php(312): mysqli->query('UPDATE `ph_sett...', 0)
#1 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `ph_sett...')
#2 C:\wamp64\www\palava_hut\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `ph_sett...')
#3 C:\wamp64\www\palava_hut\system\Database\BaseBuilder.php(2516): CodeIgniter\Database\BaseConnection->query('UPDATE `ph_sett...', Array, false)
#4 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(286): CodeIgniter\Database\BaseBuilder->update(Array, Array)
#5 C:\wamp64\www\palava_hut\app\Models\Crud_model.php(141): App\Models\Crud_model->update_where(Array, Array)
#6 C:\wamp64\www\palava_hut\app\Models\Settings_model.php(33): App\Models\Crud_model->ci_save(Array, Array)
#7 C:\wamp64\www\palava_hut\app\Controllers\Dashboard.php(41): App\Models\Settings_model->save_setting('user_1_dashboar...', '', 'user')
#8 C:\wamp64\www\palava_hut\system\CodeIgniter.php(933): App\Controllers\Dashboard->index('1')
#9 C:\wamp64\www\palava_hut\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\wamp64\www\palava_hut\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\palava_hut\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\palava_hut\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\palava_hut\index.php(75): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
